version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-image
    container_name: fastapi-service
    ports:
      - 8000:8000
    environment:
      KEY: var
